### PR TITLE
wxwidgets 3.1.4

### PR DESCRIPTION
**Pull request by ericLemanissier**
I did not change the recipe folder yet. Why was it named `3.1.3` instead of `3.1`, `3`, or even `all` ?

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Also, is there not CI any more for windows and macos ?

**Comment by Croydon** [comment]
I wanted to get rid of the `sys` value options in the next version as this is a breaking change, hence the folder name

> Also, is there not CI any more for windows and macos ?

There is, but only for Pull Requests not pushes to branches (except main)

**Comment by Croydon** [comment]
What exactly did you do an AZP to cause a duplication of the checks? 🤔
Aren't re-runs replacing them (at least for what GitHub sees)?

**Comment by ericLemanissier** [comment]
I have no idea what you are talking about. I did not touch azp. What is duplicated ? isn't it just because there are 2 versions now ?

**Comment by Croydon** [comment]
> isn't it just because there are 2 versions now ?

Yes, absolutely, forget what I just said. 🤦 😄

**Comment by ericLemanissier** [comment]
@Croydon so this is probably what you had in mind ?

**Comment by Croydon** [comment]
That is what I meant: 6ba74c08212c3e2acb7297ae517304ff64bf6266

**Review by Croydon — APPROVED** [review]
GCC 4.9 and GCC 6 fail due to a Bintray connection issue (once again)

GCC 9, Clang 8 and Clang 9 fail because of the changed system_requirements() available to the OS version (this is not a regression)

**Pull request merged**
