### PR TITLE
sdl2: remove now obsolete workaround

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Comment by Croydon** [comment]
jack can't be found anymore 👀 

e.g.

https://github.com/bincrafters/community/runs/4231750091?check_suite_focus=true#step:5:2070

**Comment by ericLemanissier** [comment]
Shouldn't we remove sdl2 ? https://github.com/bincrafters/community/pull/1414

**Comment by Croydon** [comment]
I would like to keep it around for a while longer as it isn't a full replacement yet (i.e. Jack support is missing on Linux in the CCI version)

**Comment by ericLemanissier** [comment]
Ok, so jack cannot be found because the recipe is using the conan version of pkgconf, which does not look in the packages provided by the system. A workaround is to set environment variable PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/, but it is obviously not portable across distros. Otherwise we should remove the use of conan's pkgconf, and use the system's pkg-config instead. (I have no idea why it passed before)

**Pull request closed without merging**
