### PR TITLE
imgui-sfml: changed layout of sources (bincrafters#1349)

### PR DESCRIPTION
**Pull request by fgallegosalido**
- The layout of the conandata.yml is changed so that it reflects better which sources we are accessing.
- Supported Dear ImGui versions from 1.75 through 1.79. Unfortunately, imgui-sfml 2.1 is not compatible with Dear ImGui v1.80

## Description

The main changes are in the `conandata.yml` file. It's been modified to allow better access to the sources, and also adding sources for Dear ImGui versions from 1.75 up to 1,79.

The `conanfile.py` file has been adapted to the changes of the `conandata.yml` file. It also adds the versions to the `imgui_version` options and change the default option to 1.79.

## Related Issue

#1349 

## Motivation and Context

Until now, there was no way of changing the Dear ImGui version to a more recent one. The package was stuck in version 1.75, and the most recent one is 1.80.

For that reason, an option is needed to allow the configuration of the version and not rely in an older one. This way, the user can select the specific version through the `imgui_version` option.

The layout was changed to better reflect the distribution of the sources.

Unfortunately, imgui-sfml 2.1 is not compatible with Dear ImGui v1.80, as this last version includes a new file, `imgui_tables.cpp`, which was not considered for imgui-sfml 2.1. For that reason, imgui-sfml 2.1 refuses to build with Dear ImGui v1.80. The trunk version of imgui-sfml does support v1.80, but we have to wait until a new version is released.

## How Has This Been Tested?

The specs where the changes have been tested are:
**OS**: Ubuntu 16.04 LTS
**Conan version**: 1.33.0
**Python version**: 3.8.3
**CMake version**: 3.19.3
**Hooks**: conan-center

### CODE REVIEW

**Comment by Croydon** [comment]
I have to ask this one more time because I'm still confused about this: Why seems there to be so much interest in configuring the imgui version? Using always the latest support version of imgui is not enough?

**Comment by fgallegosalido** [comment]
I was thinking more about backwards compatibility. Sure newer versions are a better choice, but it doesn't really hurt that much. For imgui-sfml 2.1, I think we must keep v1.75 for now, and add just v1.79 (as I said, v1.80+ is not compatible with imgui-sfml 2.1).

What we can do is, in every new version of imgui-sfml, support from the latest release of Dear ImGui onwards. For example, if a new version is released today, we would use Dear ImGui v1.80+.

If you really think just keeping the last version is enough, I'm totally fine with it.

**Comment by Croydon** [comment]
I never used imgui, sfml or imgui-sfml myself, so I have no clue if there are real user cases for using older versions within the range of compatible versions.

For most packages, we just use the latest compatible version for dependencies

**Comment by fgallegosalido** [comment]
In that case, I'm okay with just supporting the last version, unless someone says otherwise. But again, in the case of imgui-sfml 2.1 we cannot go higher than v1.79. We have to wait until a new version is released to bump up the version.

I can drop the support for all versions and just include the last one if you think is better.

**Comment by Croydon** [comment]
Having a look at https://github.com/bincrafters/community/issues/1125 again, I think the main concern is that we won't update the imgui version fast enough. If people provide pull requests we will happily update the imgui version regular to the latest compatible version.

So yes, I would say let's simplify this again and remove the version switch. And hence, we probably want to set the current version to 1.79

**Comment by fgallegosalido** [comment]
Before I change anything, we have to keep in mind that Dear ImGui is not really a dependency of ImGui-SFML, but rather ImGui-SFML is a SFML backend for Dear ImGui. I want to cite @eliasdaler to see his opinion about just using the last version for Dear ImGui.

**Comment by eliasdaler** [comment]
I'd say you should always use latest version of both ImGui and SFML. Both are moving forward in development quiet fast and frequently contain breaking changes between the versions.

**Comment by fgallegosalido** [comment]
In that case, I'm removing the `imgui_version` option and using Dear ImGui v1.79. When a new version of ImGui-SFML is released, I'm going to default it to the latest Dear ImGui.

Let me know if there's any further change I should consider.

**Review by Croydon — APPROVED** [review]
LGTM as it is

**Pull request merged**
