### PR TITLE
wxWidgets fails when cross-compiling; 

### LINKED ISSUE #1432: wxwidgets/3.1.5: build failure when cross compiling
In 3.1.5 wxWidgets started appending the system name to the library file names (only when cross compiling):

```
    if (CMAKE_CROSSCOMPILING)
        set(cross_target "-${CMAKE_SYSTEM_NAME}")
    endif()
```

The build fails because conanfile.py doesn't find the correct files.  While that could be fixed, this behavior probably breaks Conan compatibility.  For example if you cross compile macOS ARM from a macOS Intel machine, the library names would be different than compiling directly on a macOS ARM machine.

This behavior seems intentional so I don't think we can fix it upstream.  wxWidgets recently changed the cmake support to match the filenames from configure:

https://github.com/wxWidgets/wxWidgets/pull/2291

And affected file was updated again post 3.1.5, so a separate patch will be required for a future 3.1.6 release:

https://github.com/wxWidgets/wxWidgets/pull/2358

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **wxwidgets/3.1.5**
  * Operating System+version: **macOS 11.6**
  * Compiler+version: **apple-clang 13.0**
  * Conan version: **conan 1.41.1**
  * Python version: **Python 3.9.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
conan profile show default
```
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
os.version=10.13
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
compiler.cppstd=11
[options]
[conf]
[build_requires]
[env]
```
conan profile show armv8
```
Configuration for profile armv8:

[settings]
os=Macos
os_build=Macos
os.version=11.0
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
compiler.cppstd=11
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

conan create . wxwidgets/3.1.5@bincrafters/stable -pr armv8 -pr:b default -b missing

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
-- Build files have been written to: /Users/gmeeker/bincrafters/recipes/wxwidgets/all/test_package/build/913588727f8d8bf04520135e3e981db01271c63b
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
[100%] Linking CXX executable bin/test_package
ld: library not found for -lwx_osx_cocoau_xrc-3.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/test_package] Error 1
make[1]: *** [CMakeFiles/test_package.dir/all] Error 2
make: *** [all] Error 2
ERROR: wxwidgets/3.1.5@bincrafters/stable (test package): Error in build() method, line 12
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/Users/gmeeker/bincrafters/recipes/wxwidgets/all/test_package/build/913588727f8d8bf04520135e3e981db01271c63b' '--' '-j16'
```

</details>

Note the library names end in "-Darwin":

```
wx-config --libs
-L/Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib -pthread /Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib/libwx_osx_cocoau_xrc-3.1-Darwin.a /Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib/libwx_osx_cocoau_qa-3.1-Darwin.a /Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib/libwx_baseu_net-3.1-Darwin.a /Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib/libwx_osx_cocoau_html-3.1-Darwin.a /Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib/libwx_osx_cocoau_core-3.1-Darwin.a /Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib/libwx_baseu_xml-3.1-Darwin.a /Users/gmeeker/.conan/data/wxwidgets/3.1.5/bincrafters/stable/package/46d7b5f3a952b9ca844206da63a0a1c473e166a2/lib/libwx_baseu-3.1-Darwin.a -lwx_osx_cocoau_core-3.1-Darwin libjpeg.a libpng16.a libtiffxx.a libtiff.a -ldep_name-NOTFOUND -framework AudioToolbox -framework WebKit -lwx_baseu-3.1-Darwin libexpat.a libz.a -lwxregexu-3.1 -framework CoreFoundation -framework Security -framework Carbon -framework Cocoa -framework IOKit -framework QuartzCore 
```

### PR DESCRIPTION
**Pull request by gmeeker**
## Description
Fix library file names to match package recipe when cross compiling.

## Related Issue
closes #1432

## Motivation and Context
Corrects library names when cross compiling.  This is easy to reproduce on macOS (and probably iOS).
The current wxWidgets code in git has changed further, and I've included a 3.1.6 patch even though it hasn't been released.  The original patch is definitely 3.1.5 only (3.1.4 and early don't name the libraries this way.)

## How Has This Been Tested?
See steps in #1432 
The test recipe is able to link now.
This change affects cross compiling Linux too, although I don't think that's possible to test until a Conan GTK recipe exists?
Windows (even if cross compiled) has different library names.

### CODE REVIEW

**Comment by Croydon** [comment]
If 3.1.6 isn't yet released, can't the patch be still be included in the release?

We have a GTK Conan package for 3.x and 4.x https://conan.io/center/gtk

Is wxWidgets compatible with it?

**Comment by gmeeker** [comment]
Yeah, I guess that was confusing.  I've removed the 3.1.6 patch and I'll check back after it's released.

As for GTK, I didn't look into cross compiling Linux after finding issue #861 which I believe is where moving wxWidget to the Conan GTK package should be addressed?  It seem to be still be open (some of the Linux builds here are failing).  That issue seem to be out of date because the GTK package didn't seem to exist at the time.  I can try to take a look separately.  Can we ignore that here or would you like that to be fixed first to fully test cross compiling?

**Comment by gmeeker** [comment]
It looks like the wxWidgets recipe won't cross-compile on Linux anytime soon.  There are other system dependencies besides GTK.  This PR is effectively for macOS only.

**Comment by Croydon** [comment]
wxwidgets is now in CCI: https://github.com/conan-io/conan-center-index/pull/21353

**Pull request closed without merging**
