### PR TITLE
gst-plugins-base

### PR DESCRIPTION
**Pull request by ericLemanissier**
direct port of https://github.com/bincrafters/conan-gst-plugins-base

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Comment by ericLemanissier** [comment]
test recipe fails on macos shared with:
```
dyld: Library not loaded: /Users/jenkins/w/cci_PR-2303/.conan/data/gstreamer/1.18.0/_/_/package/23e5ccf3b9596e04f2d974d5588dadca5447c2e5/lib/libgstreamer-1.0.0.dylib
  Referenced from: /Users/runner/.conan/data/gstreamer/1.18.0/_/_/package/23e5ccf3b9596e04f2d974d5588dadca5447c2e5/bin/gstreamer-1.0/gst-plugin-scanner
  Reason: image not found
```
which already happened on travis since https://github.com/bincrafters/conan-gst-plugins-base/commit/7470e57827fc559129bcfb02dd8a7e54dddaf51f
I don't really understand why the error did not happen before this change, but it kind of usual with shared libraries on macos, it's SIP striking again. The best solution for this would be for conan to generate shims.

**Comment by Croydon** [comment]
> it's SIP striking again.

what do you mean with SIP?

**Comment by ericLemanissier** [comment]
Macos's System Integrity Protection, which sanitizes (DY)LD_LIBRARY_PATH env var. That said I'm not 100% sure it's responsible for this crash.

**Comment by ericLemanissier** [comment]
@Croydon the bot ignored the macos error ? is it intentionnal ?

**Comment by Croydon** [comment]
Damn. I fixed one bug and apparently caused another

**Comment by ericLemanissier** [comment]
whack a mole time !
image

**Comment by Croydon** [comment]
That is quite some difference... 🙈 

https://github.com/bincrafters/community/runs/1840778737?check_suite_focus=true#step:5:121

**Comment by Croydon** [comment]
Well, that bug existed before then, but was hidden by another bug.

Now I feel less bad 😄

**Pull request merged**
