### PR TITLE
introducing a CCI-style mono-repository | add sdl2/2.0.12

### PR DESCRIPTION
**Pull request by Croydon**
Merging our SDL2 recipe from a [standalone repository](https://github.com/bincrafters/conan-sdl2) into a CCI-style mono repository.

Tooling should be so far that I'm daring to open this PR. That said, there are still rough edges that I will ironing out over the next weeks or so.

I would like to continue to contribute to open source Conan mass building tooling, that supports:
  * a repository with just one recipe with one version per branch (every single Bincrafters repository so far)
  * a repository with one recipe, but many versions in a single branch
  * a CCI-style repository with many recipes and many versions in a single branch

I think that for every one of those there is a good use case.

For Bincrafters, having so many repositories is kinda painful.
  * if you update CI config files or if you update meta files like `.gitattributes` or add new ones like `.editorconfig` you have to push those changes into every single repository
  * it is hard to keep track of open pull requests and response to them accordingly
  * people from the outside are regularly confused where to report issues or where the source code is and where to open pull requests
  * if someone from the outside wants to contribute a new recipe versions, they will have to wait until a Bincrafters member is creating a new versioned branch
  * if someone from the outside wants to contribute a new recipe, they will have to wait until a Bincrafters is creating a new repository
  * switching between so many repositories so frequently is distracting 

Hence, I would like to see Bincrafters adopting a mono repository for those recipes which won't be merged tomorrow into CCI — we still have many of those. Except modular Boost that is, the tooling can't handle this, similar to CCI.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by ericLemanissier** [comment]
Did these file require any change, or are they just a copy/paste of https://github.com/bincrafters/conan-sdl2 ?

**Comment by Croydon** [comment]
I removed version `2.0.10` and the `config.yml` file is new. Beyond that it is identical.

**Review by ericLemanissier — APPROVED** [review]
Great work !

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
> if you update CI config files or if you update meta files like .gitattributes or add new ones like .editorconfig you have to push those changes into every single repository
that's really annoying, to keep repositories in sync with base templates

> if someone from the outside wants to contribute a new recipe versions, they will have to wait until a Bincrafters member is creating a new versioned branch
also painful

> it is hard to keep track of open pull requests and response to them accordingly
yeah, it's time consuming, and in the past I've missed lots of PRs because of it's hard to track so many locations

no objections, as most of popular repositories are either already moved to CCI, or moved, or planned, so it's not that breaking these days for the majority of users or contributors if we adopt new policies for bincrafters.

**Comment by Croydon** [comment]
Thank you all for the feedback!

**Pull request merged**
