### PR TITLE
Adding tips and tricks page

### PR DESCRIPTION
**Pull request by dimi309**
## Description
Adding tips and tricks page

## Related Issue
This is related to the idea we have had of adding a tips and tricks page, as described in issue #7 

## Motivation and Context
I did not want to expand too much with this initial version, but just to make a start. I have only added an introduction and a single tip. I don't know if you agree with how I describe what we do and the first piece of advice I have entered here. I think that it is normal in our mode of collaboration that it takes some time before we can agree on a piece of text such as this one. It is much easier to write code together, since the compiler regulates all differences of opinion 😄 Please feel free to make suggestions, criticize, or totally change everything!

## How Has This Been Tested?
No testing possible per se but, as I've mentioned, I am very open to suggestions.

### CODE REVIEW

**Comment by dimi309** [comment]
Thanks @uilianries ! I'm just warning you that I've added another two tips, in case you want to reconsider 😄

**Comment by solvingj** [comment]
Great work @dimi309 , thanks so much!  I did not proofread, someone please read through before merge.

**Comment by solvingj** [comment]
It's possible that for future revisions, we should separate tips and tricks into multiple files, so a directory might make sense.  Also, perhaps a better "Tip or Trick" about Cmake is to add the Conan package `cmake_installer` in the `build_requires` of your default profile.

**Comment by dimi309** [comment]
Good, good, we can split it up into files. It might be easier to also create a sort of table on contents like that. I didn't know this trick with `cmake_installer`! I'm trying it out now. So far it looks great. The thing is, I don't have a lot of experience with it yet across platforms and I would need to see if there are any quirks about it or things to watch out for before I write a tip on it. (We are supposed to be writing this document as experienced users after all 😄 ). So if anyone else is more familiar with this and would like to write something, please feel free.

**Pull request merged**
