### PR TITLE
Feature/deprecate

### PR DESCRIPTION
**Pull request by uilianries**
## Description
- Add description of deprecation flow
- Add CI support to check document format (sphinx)
- Fix minor changes (typo, title, subtitle...)

## Related Issue
* #546 

## Motivation and Context
* Describe how to deprecate a package step-by-step

## How Has This Been Tested?
1) Create a dummy conan package
2) Follow the steps listed on *Strategy for deprecating packages*
3) Compare to PEGTL and Catch2 projects

### CODE REVIEW

**Comment by solvingj** [comment]
Looks really good to me. Ok to merge when done building.

**Comment by uilianries** [comment]
@Cryodon could you please review/comment?

**Comment by Croydon** [comment]
Looks pretty good to me. Maybe we should add information for what I described here as a "soft transition version" https://github.com/bincrafters/community/issues/546#issuecomment-444057900

Meaning in the case that a library got upstream Conan support in a new version, we are adding this version to Bincrafters with the warning/alias. 

This has the effect, that people are on the following update path
  * something/1.0.0@bincrafters/stable
  * -> updating to something/1.1.0@bincrafters/stable which contains warning and alias 
  * -> using something/1.1.0@upstream/stable directly in a next step

That would allow a soft transition as consumers don't need to change the origin of the recipe and update their dependencies at the same time.

**Comment by uilianries** [comment]
Done, I've added step 0, where should be created a new branch version to execute a soft transition.

**Pull request merged**
