### PR TITLE
add gtk/3.24.22

### PR DESCRIPTION
**Pull request by Croydon**
Ported from https://github.com/bincrafters/conan-gtk

### CODE REVIEW

**Comment by Croydon** [comment]
The error is

```
libgettext/0.20.1: WARN: Recipe 'libgettext/0.20.1' is deprecated in favor of 'gettext'. Please, consider changing your requirements.
WARN: atk/2.36.0: requirement glib/2.66.2 overridden by gtk/3.24.22@bincrafters/testing to glib/2.67.0 
ERROR: Missing binary: gdk-pixbuf/2.42.0@bincrafters/stable:7205e2a4e5f16ed5ec944effd18307e36fa97a6c
gdk-pixbuf/2.42.0@bincrafters/stable: WARN: Can't find a 'gdk-pixbuf/2.42.0@bincrafters/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.version=11.0, os=Macos
- Options: fPIC=True, shared=False, with_jasper=False, with_libjpeg=True, with_libpng=True, with_libtiff=True, bzip2:build_executable=True, bzip2:fPIC=True, bzip2:shared=False, glib:fPIC=True, glib:shared=False, glib:with_elf=True, glib:with_pcre=True, jbig:build_executables=True, jbig:fPIC=True, jbig:shared=False, libelf:fPIC=True, libelf:shared=False, libffi:fPIC=True, libffi:shared=False, libgettext:fPIC=True, libgettext:shared=False, libiconv:fPIC=True, libiconv:shared=False, libjpeg:fPIC=True, libjpeg:shared=False, libpng:api_prefix=None, libpng:fPIC=True, libpng:shared=False, libtiff:cxx=True, libtiff:fPIC=True, libtiff:jbig=True, libtiff:jpeg=libjpeg, libtiff:lzma=True, libtiff:shared=False, libtiff:zlib=True, pcre:build_pcre_16=True, pcre:build_pcre_32=True, pcre:build_pcre_8=True, pcre:build_pcrecpp=False, pcre:build_pcregrep=True, pcre:fPIC=True, pcre:shared=False, pcre:with_bzip2=True, pcre:with_jit=False, pcre:with_unicode_properties=False, pcre:with_utf=False, pcre:with_zlib=True, xz_utils:fPIC=True, xz_utils:shared=False, zlib:fPIC=True, zlib:minizip=False, zlib:shared=False
- Dependencies: glib/2.67.0, libpng/1.6.37, libtiff/4.0.9, libjpeg/9d
- Requirements: glib/2.Y.Z, libjpeg/9d, libpng/1.Y.Z, libtiff/4.Y.Z
- Package ID: 7205e2a4e5f16ed5ec944effd18307e36fa97a6c
```

https://dev.azure.com/bincrafters/packages/_build/results?buildId=8542&view=logs&j=522e8de8-2df9-5cd7-5877-3ec17328ce1d&t=e58e9087-8b60-5fb8-36e0-6f882f2f0554&l=408

**Comment by ericLemanissier** [comment]
yes, it occured also on https://travis-ci.com/github/bincrafters/conan-gtk/builds/201463924
This is because gdk-pixbuf does not build on macos since the transition of glib to CCI : https://travis-ci.com/github/bincrafters/conan-gdk-pixbuf/jobs/439829508#L1230
I have no clue how to solve this one :/

**Review by ericLemanissier — DISMISSED** [review]

**Comment by Croydon** [comment]
I'm conflicted between merging this since it does not seem to make the situation worse as it already is and leaving it open until we have a fix

**Comment by ericLemanissier** [comment]
now that [gdk-pixbuf raises `ConanInvalidConfiguration` on macos](https://github.com/conan-io/conan-center-index/blob/master/recipes/gdk-pixbuf/all/conanfile.py), Do you think we can merge this one ?

**Comment by Croydon** [comment]
As long as we don't forget to check out macOS support one day again  👍  

GCC 4.9 needs raising or fixing

**Comment by ericLemanissier** [comment]
merged directly on CCI

**Pull request closed without merging**
